pf ref commands should reject directory names passed for symlink creation
sanger-pathogens/Bio-Path-Find pull request #114
Opened 2022-08-16 11:48 UTC by trstickland

Usually the `-l`/`--symlink` option takes a directory name (e.g. when used with `pf data`), but with `pf ref` commands that causes an error.   If the users does this, it should cause an error with a suitable message.

(`pf ref` can take this option without a value, or with name that should be used for the new symlink.)

2022-08-16 12:47 UTC, Lfulcrum requested changes

2022-08-16 12:47 UTC, Lfulcrum commented on lib/Bio/Path/Find/App/PathFind/Ref.pm
> +    # *should* provide a directory name; so it is a likely cause of confusuon for users)
```suggestion
    # *should* provide a directory name; so it is a likely cause of confusion for users)
```

2022-09-02 12:36 UTC, trstickland commented
Docker build fixed

2022-09-02 12:39 UTC, trstickland commented
Docker build fixed

Requires dzil install uses `--notest`.  This requires tests have been run on devel machine, to be safe.

2022-09-02 12:41 UTC, trstickland commented on lib/Bio/Path/Find/App/PathFind/Ref.pm
> +    # *should* provide a directory name; so it is a likely cause of confusuon for users)
Fixed

2022-09-02 13:09 UTC, trstickland commented
@Lfulcrum when this is merged and tagged we can check the automated docker build, to see if it is still being triggered

2022-09-06 08:51 UTC, Lfulcrum approved these changes
LGTM

2022-09-06 09:28 UTC, merged